import React, { useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { SectionContainer } from './SectionContainer';
import { ArticleItem } from '../types';
import { motion, AnimatePresence } from 'framer-motion';

const articlesData: ArticleItem[] = [
  {
    id: '1',
    title: 'AWS VPC: Your Private Network in the Cloud',
    summary: 'A practical guide to understanding Virtual Private Clouds, subnets, security groups, and real-world architecture — explained with analogies.',
    category: 'AWS',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCAy4xiXjrH9ymXkQvSh8MiB3pCQJI7G8PuN9EEDg2NXGgbGjupgK8YnCS17RRhQ_ac3gj9luWCp8j3cCnUJgXenpDT_D8ZE5UCEozmLcKwbQv9NhW9FjMRKg87ZjYm4Rz29oeCZ18WcKXAVQLJkuLBUuE-idXM8JHve7UE7XIywXJiC8lijVABX-z2_f2g2SB7mkjQHGQBZEGkCM6ZME4dkz0WPyqXKHXYG48AtBiqjklq0nVV8M5M1C6I2aA5LTe2spb_XEs3E6K0',
    url: 'https://sarathy-r.medium.com/aws-vpc-your-private-network-in-the-cloud-a67133ee92a5'
  },
  {
    id: '2',
    title: 'Design Patterns in Python',
    summary: 'Exploring common design patterns and their implementation in Python for writing more maintainable and scalable code.',
    category: 'Python',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    url: 'https://sarathy-r.medium.com/design-patterns-in-python-11dad6ef902e'
  },
  {
    id: '3',
    title: 'Prompt Tips for Developers -Helps you to write better prompts — Part 1',
    summary: 'This guide walks through clear, developer-focused techniques to improve the quality of code generated by LLMs. Each section includes examples, tables, and technical insights suitable for intermediate programmers.',
    category: 'AI',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    url: 'https://sarathy-r.medium.com/writing-better-prompts-tips-for-developer-part-1-d6f8d4e6b83d'
  },
    {
    id: '4',
    title: 'Modern Python: Staying up to date',
    summary: 'If you haven’t updated your coding patterns since Python 3.7, you’re missing out on features that make your scripts significantly cleaner.',
    category: 'Python',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    url: 'https://medium.com/@sarathy-r/modern-python-staying-up-to-date-10ab931d202a'
  }
];

const categories = ['All', 'Python', 'AWS', 'AI'];

export const Articles: React.FC = () => {
  const [activeCategory, setActiveCategory] = useState('All');

  const filteredArticles = activeCategory === 'All' 
    ? articlesData 
    : articlesData.filter(article => article.category === activeCategory);

  return (
    <SectionContainer id="articles">
      <h2 className="mb-10 px-4 text-3xl font-bold leading-tight tracking-tighter text-gray-900 dark:text-white sm:text-4xl">
        Article Publications
      </h2>
      
      {/* Filters */}
      <div className="mb-12 flex flex-wrap gap-3 px-4">
        {categories.map(category => (
          <button
            key={category}
            onClick={() => setActiveCategory(category)}
            className={`rounded-full px-5 py-2 text-sm font-bold transition-all duration-300 hover:scale-105 ${
              activeCategory === category
                ? 'bg-primary text-white shadow-lg shadow-primary/30'
                : 'bg-gray-200 text-gray-600 hover:bg-gray-300 hover:text-gray-900 dark:bg-surface-dark dark:text-white/70 dark:hover:bg-white/20 dark:hover:text-white'
            }`}
          >
            {category}
          </button>
        ))}
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 gap-8 px-4 sm:grid-cols-2 lg:grid-cols-3">
        <AnimatePresence mode="popLayout">
          {filteredArticles.map((article) => (
            <motion.a
              href={article.url}
              target="_blank"
              rel="noopener noreferrer"
              key={article.id}
              layout
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.3 }}
              className="group flex flex-col overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-lg transition-all duration-300 hover:-translate-y-3 hover:shadow-2xl hover:shadow-primary/10 dark:border-transparent dark:bg-surface-dark cursor-pointer"
              style={{ textDecoration: 'none' }}
            >
              <div 
                className="h-56 w-full bg-cover bg-center transition-transform duration-700 group-hover:scale-110"
                style={{ backgroundImage: `url('${article.imageUrl}')` }}
              />
              <div className="flex flex-grow flex-col p-6">
                <div className="mb-4 flex items-center justify-between">
                   <span className="rounded bg-primary/5 dark:bg-background-dark/80 backdrop-blur-sm px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-primary border border-primary/20">
                     {article.category}
                   </span>
                </div>
                <h3 className="mb-3 text-xl font-bold leading-snug text-gray-900 dark:text-white group-hover:text-primary transition-colors">
                  {article.title}
                </h3>
                <p className="mb-6 flex-grow text-sm leading-relaxed text-gray-600 dark:text-gray-400">
                  {article.summary}
                </p>
                <span 
                  className="inline-flex items-center text-sm font-bold text-primary transition-colors hover:text-primary/80"
                >
                  Read More <ArrowRight size={18} className="ml-2 transition-transform duration-300 group-hover:translate-x-2" />
                </span>
              </div>
            </motion.a>
          ))}
        </AnimatePresence>
      </div>
    </SectionContainer>
  );
};
